### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by edwinb-ai** [GuillaumeLam/LiquidStateMachine.jl#1]
Hello @GuillaumeLam ! I am trying to learn and implement a Liquid State Machine in Julia, and came across your package. Looks great!
Just wondering if you needed some help with the package, I would love to help out while learning along.

Also, is there somewhere we could chat, maybe on Slack or something like that? I wanted to ask some questions I have regarding LSM themselves. Thanks a lot!

**Comment by GuillaumeLam** [comment]
Hey Edwin! Thanks for the interest in the repo! I would absolutely be ecstatic if you would want to contribute to the package.
I am free to chat today 4h30-5h30 EST or even tmrw (free all day)! We can communicate through the julia slack if that works for you! We can even zoom or smth, whatever works!

**Comment by edwinb-ai** [comment]
Fantastic! You can find me on the Julia Slack as @ Edwin Bedolla, I think. If you could send me a message, we can get the collaboration going. Thanks for your time!
